const snap = [
  {
    id: '0',
    name: 'Sentiment Analysis',
    description:
      'Analyze the sentiment of a product review to identify whether review contains complaints. Return just the overall doc sentiment.',
    type: 'llm',
    aggregate: false,
    prompt:
      'Analyze the sentiment of the provided product review and determine whether it contains complaints. Return only the overall sentiment of the review, indicating if it is positive, negative, or neutral.',
    testResults: [
      {
        docId: '0',
        result: 'The overall sentiment of the review is positive.',
      },
      {
        docId: '1',
        result: 'Negative',
      },
      {
        docId: '2',
        result:
          "The overall sentiment of the review is negative. It contains several complaints about gameplay mechanics, matchmaking issues, and map generation, which contribute to the reviewer's frustration and dissatisfaction with the game.",
      },
    ],
  },
  {
    id: '1',
    name: 'Extract overall document sentiment',
    description:
      'Extract overall document sentiment from textual description of sentiment generated by LLM. Resulting sentiment should be either "Negative" or return nothing for positive docs to filter them out.',
    type: 'code',
    aggregate: false,
    prompt:
      "```javascript\nexport default function extractOverallDocumentSentiment(sentimentDescription) {\n    const negativeKeywords = ['bad', 'terrible', 'awful', 'poor', 'negative', 'hate', 'dislike', 'sad', 'unhappy'];\n    \n    const isNegative = negativeKeywords.some(keyword => \n        sentimentDescription.toLowerCase().includes(keyword)\n    );\n\n    return isNegative ? 'Negative' : '';\n}\n```",
    testResults: [
      {
        docId: '0',
        result: '',
      },
      {
        docId: '1',
        result: 'Negative',
      },
      {
        docId: '2',
        result: 'Negative',
      },
    ],
  },
  {
    id: '2',
    name: 'Extract complaints from product review',
    description:
      'Analyze a product review to identify complaints. Return just the list of complaints.',
    type: 'llm',
    aggregate: false,
    prompt:
      'Please analyze the provided product review and extract all complaints mentioned within it. Return only a list of these complaints without any additional information or context.',
    testResults: [
      {
        docId: '1',
        result:
          "1. Nerfed fire damage to the point it can't kill armored enemies or crowds.\n2. Frustration with the balance philosophy that removes fun elements from the game.\n3. Repeated instances of fun being taken away since purchasing the game.\n4. Considering uninstalling the game due to dissatisfaction.",
      },
      {
        docId: '2',
        result:
          "1. The act of getting ready to play feels onerous.\n2. Public random quickplay matches involve sweaty players who get angry and leave samples behind.\n3. Inability to report players who block you.\n4. Difficulty in finding a suitable loadout other than being an autocannon mule.\n5. Unlocked items are either ineffective or require a gross meta shotgun.\n6. Feels wasteful to pilot mechs.\n7. Map generation can create unwinnable situations.\n8. Poor ammo economy leads to a jogging simulator experience.\n9. Fire damage can kill instantly.\n10. Limited variety in map conditions (e.g., fighting in dense fog).\n11. Earthquakes sap stamina for no clear reason.\n12. Trash mobs soak up too much regular ammo.\n13. Specials ignore regular primary ammo.\n14. Sony's blockade of countries has ended further support.",
      },
      {
        docId: '1',
        result:
          '1. Nerfed fire damage, making it ineffective against armored enemies and crowds.\n2. Balance philosophy that removes enjoyable elements instead of adding new options.\n3. Repeated instances of fun being taken away since the reviewer bought the game.\n4. Frustration leading to thoughts of uninstalling the game and playing something else.',
      },
    ],
  },
  {
    id: '3',
    name: 'Summarize common complaints',
    description: 'Summarize the most frequent complaints in given documents.',
    type: 'llm',
    aggregate: true,
    prompt:
      'Please analyze the provided text document and identify the most common complaints mentioned within it. Summarize these complaints clearly and concisely, highlighting the key issues that are frequently raised.',
    testResults: [
      {
        docId: 'aggregate',
        result:
          "The text document outlines several common complaints from players, which can be summarized as follows:\n\n1. **Gameplay Balance Issues**:\n   - Fire damage has been nerfed excessively, making it ineffective against armored enemies and in crowd situations.\n   - Players express frustration with the game's balance philosophy, feeling it detracts from enjoyment and fun elements.\n   - There are repeated grievances about fun features being removed since the game's purchase.\n\n2. **Matchmaking and Player Behavior**:\n   - Players find the process of getting ready to play cumbersome and onerous.\n   - Public quickplay matches are described as being filled with highly competitive players who exhibit toxic behavior, leading to a negative experience.\n   - There is a lack of reporting options for players who block others, contributing to frustration.\n\n3. **Loadout and Equipment Concerns**:\n   - Difficulty in finding effective loadouts, with players feeling forced into suboptimal choices like being an \"autocannon mule.\"\n   - Unlocked items are often seen as ineffective or reliant on a specific meta strategy, such as using a shotgun.\n\n4. **Game Mechanics and Environment**:\n   - Players feel that piloting mechs is wasteful, possibly due to poor design or mechanics.\n   - Map generation can lead to unwinnable scenarios, impacting overall gameplay experience.\n   - The game's ammo economy is criticized, leading to a feeling of being reduced to a \"jogging simulator.\"\n\n5. **Environmental Effects and Variety**:\n   - Limited variety in map conditions, such as recurring dense fog, detracts from gameplay.\n   - Environmental effects like earthquakes are seen as frustrating, with unclear reasons for their impact on gameplay.\n   - Trash mobs absorb too much ammo, complicating combat.\n\n6. **Support and Development Issues**:\n   - Players express dissatisfaction with the end of support due to Sony's blockade of certain countries, leading to concerns about the game's future.\n\nOverall, the primary complaints focus on gameplay balance, player behavior in matches, loadout effectiveness, game mechanics, environmental variety, and concerns regarding ongoing support for the game.",
      },
    ],
  },
];
