name: Test and lint

on:
  release:
    types: [published]
  push:
    paths-ignore:
      - '**/*.md' # Ignore changes to markdown files
  pull_request:
    paths-ignore:
      - '**/*.md' # Ignore changes to markdown files

jobs:
  test-lint:
    environment: Github CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test and lint
        uses: ./.github/actions/test-lint
